spring.datasource.url=jdbc:mysql://localhost:3306/techzone?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JSP Path Mapping
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Optional: Disable Whitelabel Error Page for custom mapping
server.error.whitelabel.enabled=false
